# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QuocCuongProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  pod 'Alamofire', '~> 4.7'
  pod 'IQKeyboardManagerSwift' 
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'

  

  # Pods for QuocCuongProject

  target 'QuocCuongProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QuocCuongProjectUITests' do
    # Pods for testing
  end

end
